### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [Alex-Holyk/BSA-17-JS.Lecture-1-Git-Homework#10]
@Alex-Holyk я вже здається залишав тобі проблему в **Issues**, але здається то був інший репозиторій, який ти успішно випиляв... _(но ет нє точна)_

Давай додамо **README.md** до репозиторію? З описом проекту, коротким, в абзац. І ще можна посилання на твої файли додати — ну, хоча б через те, що так зручніше буде серфити. [**А ще почитай лайфхаків трохи, будь ласка.**](https://github.com/volodymyr-kushnir/agenda)

**Comment by Alex-Holyk** [comment]
@volodymyr-kushnir так, той репозиторій був тренувальним. Я вже пізніше на пошті побачив, що там коментували. Соррі)

**Comment by Alex-Holyk** [comment]
@volodymyr-kushnir додав файл README.md та посилання на файли. Почитав лайфхаки і зрозумів, як потрібно організовувати проект в Projects. Дякую за допомогу :+1:
